// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { databaseUrl } from "./src/configs";

const isProduction = process.env.NODE_ENV === "production";
const schema =
  process.env.PRISMA_SCHEMA ??
  (isProduction ? "prisma/schema.postgres.template" : "prisma/schema.prisma");
const migrationsPath = schema.includes("postgres")
  ? "prisma/migrations-postgres"
  : "prisma/migrations-sqlite";

export default defineConfig({
  schema,
  migrations: {
    path: migrationsPath,
  },
  datasource: {
    url: databaseUrl,
  },
});
